### PR TITLE
Merged with metafor.Rmd

### LINKED ISSUE #23: Include Rh_annual and Rs_growing season

### LINKED ISSUE #27: SP Synthesis 3/22
- [x] Integrate `metafor.Rmd` and `rs-synthesis.Rmd` to resolve #23 
- [x] Set up folder for Shoshi to go through the 2018+ Rs studies
- [x] Inventory PR
- [x] Help Shoshi get started on data entry for the new studies

### PR DESCRIPTION
**Pull request by stephpenn1**
### Do not merge yet until review / discussion w @bpbond 

This commit:
- adds code from `metafor.Rmd` 
- Comments out drainage type code for now
- removes duplicated tables and adds interactive capabilities to main summary table
- Resolves #23 and closes #27 

This commit does not:
- resolve potential duplication in the variance data sheet and the `srdb` variable (the var that originally searched for studies)
- address the potential for duplicated code when we apply this to drainage type

### CODE REVIEW

**Comment by bpbond** [comment]
Nice break-test-diagnose-and-fix 👍 

For the table summary, it might be more useful and easier to read if different manipulations were spread across columns? We can discuss.

**Comment by stephpenn1** [comment]
Oh interesting, let's put that on the agenda for tomorrow

**Review by bpbond — APPROVED** [review]

**Comment by stephpenn1** [comment]
I will:
- [ ] Join `srdb` with google sheet 
- [ ] spread the table summary for readability

**Comment by stephpenn1** [comment]
Updated table: (@bpbond)
Screen Shot 2021-04-05 at 6 08 48 PM

**Comment by stephpenn1** [comment]
Updated table shows number of studies that include either Rs_annual, Rs_growingseason, or Rh_annual by manipulation in forest ecosystems: (@bpbond)

Screen Shot 2021-04-05 at 6 11 04 PM

**Comment by bpbond** [comment]
@stephpenn1 The table looks useful—what do you think?

...but also probably wrong. Why are all the numbers identical in the three columns? I would guess the code is counting _rows_ and not non-NA _entries_, which is what it should.

**Comment by stephpenn1** [comment]
Oh you are so right. Brb

**Pull request merged**
